name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Build
        shell: powershell
        run: Get-ChildItem -Path . -Include *.sln -Recurse | ForEach-Object {dotnet build $_}
      - name: Run tests
        shell: powershell
        run: Get-ChildItem -Path . -Include *.sln -Recurse | ForEach-Object {dotnet test $_}